title: "VR-Labor HS-KL"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
# Inhaltsverzeichnis links im Browser erzeugen
has_toc: true
# Logo file
logo: "hurricaneVis.png"
