title: "VR-Labor Hochschule Kaiserslautern Standort Zweibrücken"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
# Inhaltsverzeichnis links im Browser erzeugen
has_toc: false
# Logo file
logo: "hurricaneVis.png"
